name: Go

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: src/github.com/ikawaha/kanji

      - name: Set up Go 1.x
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: src/github.com/ikawaha/kanji/go.mod

      - name: Build
        run: go build -v ./...
        working-directory: src/github.com/ikawaha/kanji

      - name: Test
        run: |
          go test -v ./...
        working-directory: src/github.com/ikawaha/kanji

