name: Go

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: src/github.com/ikawaha/kanji

      - name: Set up Go 1.x
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: src/github.com/ikawaha/kanji/go.mod

      - name: Build
        run: go build -v ./...
        working-directory: src/github.com/ikawaha/kanji

      - name: Test
        run: |
          go test -v ./...
        working-directory: src/github.com/ikawaha/kanji

